### ISSUE TITLE
Not working for a handful of scripts

### ISSUE THREAD

**Issue by OG-CYPHA** [cwolff411/powerob#1]
This worked for PowerUp.ps1 but would not work on Invoke-Mimikatz or Out-Minidump. I tried on a handful other scripts, some worked, some didnt, but the two above were the most notable.
Errors out while looking for functions -

**Comment by cwolff411** [comment]
Thanks for the heads up. It was an issue with the regex. Latest commit should fix it.

**Comment by OG-CYPHA** [comment]
This is an awesome tool, and that is also a quick reaction time. Thanks for what you do. Also, I am happy to test anytime :) 

Speaking of testing, still having the same error with Out-Minidump, although it now works for Invoke-Mimikatz!

**Comment by cwolff411** [comment]
Thanks, I appreciate the kind words. It's definitely something to do with the regex. I'll check it out.

**Comment by cwolff411** [comment]
Oh! Sorry just realized that there are no functions in out-minidump. v1 will only work with functions. Something for v2!
